/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * A photo carousel: a main image with prev/next buttons, an optional
     * "n / total" counter, and an optional thumbnail strip — driven by
     * keyboard (arrow keys), touch (swipe), and mouse alike.
     * Consolidates the two carousels that used to be hand-rolled independently
     * for the recipe detail hero and the recipe-form photo preview: same
     * WAI-ARIA pattern (a focusable `role="group"` region owning arrow-key
     * nav, with prev/next also reachable as real buttons), same swipe
     * gesture, same broken-image handling — just themed differently via
     * `counterPosition`/`thumbsLayout` and the `--rc-carousel-*` CSS
     * properties instead of two copies of the logic.
     */
    interface RcPhotoCarousel {
        /**
          * Initial/controlled slide index.
          * @default 0
         */
        "activeIndex": number;
        /**
          * Alt text for the main image (e.g. the recipe name). Thumbnails are decorative.
          * @default ''
         */
        "alt": string;
        /**
          * Where the counter pill sits over the image.
          * @default 'top-right'
         */
        "counterPosition": 'top-right' | 'bottom-right';
        /**
          * Image URLs to show. A single image renders without any nav chrome.
          * @default []
         */
        "images": string[];
        /**
          * Accessible label for the carousel region, e.g. "Recipe photos".
          * @default 'Photos'
         */
        "label": string;
        /**
          * Show the "n / total" counter when there's more than one photo.
          * @default true
         */
        "showCounter": boolean;
        /**
          * Show the thumbnail strip when there's more than one photo.
          * @default true
         */
        "showThumbs": boolean;
        /**
          * `overlay` floats thumbnails over the bottom of the image (recipe hero); `inline` places them in normal flow below it (form preview, smaller card).
          * @default 'overlay'
         */
        "thumbsLayout": 'overlay' | 'inline';
    }
    /**
     * A card that displays a recipe summary.
     * Consumers pass recipe data via props and listen for the `favoriteToggle`
     * custom event to react to favorite/unfavorite clicks. A named `actions`
     * slot lets the host app inject extra buttons (e.g. "Edit", "Delete") —
     * they appear as an overlay on the image, revealed on hover/focus.
     */
    interface RcRecipeCard {
        /**
          * Short category / cuisine label, e.g. "Dessert" or "Italian".
         */
        "category"?: string;
        /**
          * Image URL for the recipe.
         */
        "image"?: string;
        /**
          * Whether this recipe is currently in the user's favorites.
          * @default false
         */
        "isFavorite": boolean;
        /**
          * Optional one-line meta string shown under the title, e.g. "32m · Italian".
         */
        "meta"?: string;
        /**
          * Recipe title.
         */
        "name": string;
        /**
          * Recipe unique id, forwarded back on events so the host can identify the recipe.
         */
        "recipeId": string;
        /**
          * Optional secondary badge shown at the top-left of the image, e.g. "Mine" to mark a user-authored recipe apart from the category chip.
         */
        "secondaryBadge"?: string;
        /**
          * Visual size variant. `featured` is used for editorial hero-style spots in the grid.
          * @default 'default'
         */
        "variant": 'default' | 'featured';
    }
    /**
     * A search input with a submit button. Extra filter controls (selects,
     * checkboxes, etc.) can be projected via the default slot, so the host
     * app controls filter UI while this component only owns the text query.
     */
    interface RcSearchBar {
        /**
          * Placeholder text.
          * @default 'Search recipes…'
         */
        "placeholder": string;
        /**
          * Initial/controlled value of the search input.
          * @default ''
         */
        "value": string;
    }
    /**
     * An interactive (or read-only) star rating control.
     * Used e.g. on the recipe details page for the user to rate a recipe.
     */
    interface RcStarRating {
        /**
          * Max number of stars.
          * @default 5
         */
        "max": number;
        /**
          * When false, stars are display-only (no hover/click interaction).
          * @default false
         */
        "readonly": boolean;
        /**
          * Current rating value.
          * @default 0
         */
        "value": number;
    }
}
export interface RcPhotoCarouselCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRcPhotoCarouselElement;
}
export interface RcRecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRcRecipeCardElement;
}
export interface RcSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRcSearchBarElement;
}
export interface RcStarRatingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRcStarRatingElement;
}
declare global {
    interface HTMLRcPhotoCarouselElementEventMap {
        "slideChange": { index: number };
    }
    /**
     * A photo carousel: a main image with prev/next buttons, an optional
     * "n / total" counter, and an optional thumbnail strip — driven by
     * keyboard (arrow keys), touch (swipe), and mouse alike.
     * Consolidates the two carousels that used to be hand-rolled independently
     * for the recipe detail hero and the recipe-form photo preview: same
     * WAI-ARIA pattern (a focusable `role="group"` region owning arrow-key
     * nav, with prev/next also reachable as real buttons), same swipe
     * gesture, same broken-image handling — just themed differently via
     * `counterPosition`/`thumbsLayout` and the `--rc-carousel-*` CSS
     * properties instead of two copies of the logic.
     */
    interface HTMLRcPhotoCarouselElement extends Components.RcPhotoCarousel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRcPhotoCarouselElementEventMap>(type: K, listener: (this: HTMLRcPhotoCarouselElement, ev: RcPhotoCarouselCustomEvent<HTMLRcPhotoCarouselElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRcPhotoCarouselElementEventMap>(type: K, listener: (this: HTMLRcPhotoCarouselElement, ev: RcPhotoCarouselCustomEvent<HTMLRcPhotoCarouselElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRcPhotoCarouselElement: {
        prototype: HTMLRcPhotoCarouselElement;
        new (): HTMLRcPhotoCarouselElement;
    };
    interface HTMLRcRecipeCardElementEventMap {
        "favoriteToggle": { recipeId: string; isFavorite: boolean };
        "cardSelect": { recipeId: string };
    }
    /**
     * A card that displays a recipe summary.
     * Consumers pass recipe data via props and listen for the `favoriteToggle`
     * custom event to react to favorite/unfavorite clicks. A named `actions`
     * slot lets the host app inject extra buttons (e.g. "Edit", "Delete") —
     * they appear as an overlay on the image, revealed on hover/focus.
     */
    interface HTMLRcRecipeCardElement extends Components.RcRecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRcRecipeCardElementEventMap>(type: K, listener: (this: HTMLRcRecipeCardElement, ev: RcRecipeCardCustomEvent<HTMLRcRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRcRecipeCardElementEventMap>(type: K, listener: (this: HTMLRcRecipeCardElement, ev: RcRecipeCardCustomEvent<HTMLRcRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRcRecipeCardElement: {
        prototype: HTMLRcRecipeCardElement;
        new (): HTMLRcRecipeCardElement;
    };
    interface HTMLRcSearchBarElementEventMap {
        "searchInput": { query: string };
        "searchSubmit": { query: string };
    }
    /**
     * A search input with a submit button. Extra filter controls (selects,
     * checkboxes, etc.) can be projected via the default slot, so the host
     * app controls filter UI while this component only owns the text query.
     */
    interface HTMLRcSearchBarElement extends Components.RcSearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRcSearchBarElementEventMap>(type: K, listener: (this: HTMLRcSearchBarElement, ev: RcSearchBarCustomEvent<HTMLRcSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRcSearchBarElementEventMap>(type: K, listener: (this: HTMLRcSearchBarElement, ev: RcSearchBarCustomEvent<HTMLRcSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRcSearchBarElement: {
        prototype: HTMLRcSearchBarElement;
        new (): HTMLRcSearchBarElement;
    };
    interface HTMLRcStarRatingElementEventMap {
        "ratingChange": { value: number };
    }
    /**
     * An interactive (or read-only) star rating control.
     * Used e.g. on the recipe details page for the user to rate a recipe.
     */
    interface HTMLRcStarRatingElement extends Components.RcStarRating, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRcStarRatingElementEventMap>(type: K, listener: (this: HTMLRcStarRatingElement, ev: RcStarRatingCustomEvent<HTMLRcStarRatingElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRcStarRatingElementEventMap>(type: K, listener: (this: HTMLRcStarRatingElement, ev: RcStarRatingCustomEvent<HTMLRcStarRatingElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRcStarRatingElement: {
        prototype: HTMLRcStarRatingElement;
        new (): HTMLRcStarRatingElement;
    };
    interface HTMLElementTagNameMap {
        "rc-photo-carousel": HTMLRcPhotoCarouselElement;
        "rc-recipe-card": HTMLRcRecipeCardElement;
        "rc-search-bar": HTMLRcSearchBarElement;
        "rc-star-rating": HTMLRcStarRatingElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * A photo carousel: a main image with prev/next buttons, an optional
     * "n / total" counter, and an optional thumbnail strip — driven by
     * keyboard (arrow keys), touch (swipe), and mouse alike.
     * Consolidates the two carousels that used to be hand-rolled independently
     * for the recipe detail hero and the recipe-form photo preview: same
     * WAI-ARIA pattern (a focusable `role="group"` region owning arrow-key
     * nav, with prev/next also reachable as real buttons), same swipe
     * gesture, same broken-image handling — just themed differently via
     * `counterPosition`/`thumbsLayout` and the `--rc-carousel-*` CSS
     * properties instead of two copies of the logic.
     */
    interface RcPhotoCarousel {
        /**
          * Initial/controlled slide index.
          * @default 0
         */
        "activeIndex"?: number;
        /**
          * Alt text for the main image (e.g. the recipe name). Thumbnails are decorative.
          * @default ''
         */
        "alt"?: string;
        /**
          * Where the counter pill sits over the image.
          * @default 'top-right'
         */
        "counterPosition"?: 'top-right' | 'bottom-right';
        /**
          * Image URLs to show. A single image renders without any nav chrome.
          * @default []
         */
        "images"?: string[];
        /**
          * Accessible label for the carousel region, e.g. "Recipe photos".
          * @default 'Photos'
         */
        "label"?: string;
        /**
          * Fired whenever the active slide changes, however it was triggered.
         */
        "onSlideChange"?: (event: RcPhotoCarouselCustomEvent<{ index: number }>) => void;
        /**
          * Show the "n / total" counter when there's more than one photo.
          * @default true
         */
        "showCounter"?: boolean;
        /**
          * Show the thumbnail strip when there's more than one photo.
          * @default true
         */
        "showThumbs"?: boolean;
        /**
          * `overlay` floats thumbnails over the bottom of the image (recipe hero); `inline` places them in normal flow below it (form preview, smaller card).
          * @default 'overlay'
         */
        "thumbsLayout"?: 'overlay' | 'inline';
    }
    /**
     * A card that displays a recipe summary.
     * Consumers pass recipe data via props and listen for the `favoriteToggle`
     * custom event to react to favorite/unfavorite clicks. A named `actions`
     * slot lets the host app inject extra buttons (e.g. "Edit", "Delete") —
     * they appear as an overlay on the image, revealed on hover/focus.
     */
    interface RcRecipeCard {
        /**
          * Short category / cuisine label, e.g. "Dessert" or "Italian".
         */
        "category"?: string;
        /**
          * Image URL for the recipe.
         */
        "image"?: string;
        /**
          * Whether this recipe is currently in the user's favorites.
          * @default false
         */
        "isFavorite"?: boolean;
        /**
          * Optional one-line meta string shown under the title, e.g. "32m · Italian".
         */
        "meta"?: string;
        /**
          * Recipe title.
         */
        "name": string;
        /**
          * Fired when the card body (not a button) is clicked — host can navigate to details.
         */
        "onCardSelect"?: (event: RcRecipeCardCustomEvent<{ recipeId: string }>) => void;
        /**
          * Fired when the favorite (heart) button is clicked.
         */
        "onFavoriteToggle"?: (event: RcRecipeCardCustomEvent<{ recipeId: string; isFavorite: boolean }>) => void;
        /**
          * Recipe unique id, forwarded back on events so the host can identify the recipe.
         */
        "recipeId": string;
        /**
          * Optional secondary badge shown at the top-left of the image, e.g. "Mine" to mark a user-authored recipe apart from the category chip.
         */
        "secondaryBadge"?: string;
        /**
          * Visual size variant. `featured` is used for editorial hero-style spots in the grid.
          * @default 'default'
         */
        "variant"?: 'default' | 'featured';
    }
    /**
     * A search input with a submit button. Extra filter controls (selects,
     * checkboxes, etc.) can be projected via the default slot, so the host
     * app controls filter UI while this component only owns the text query.
     */
    interface RcSearchBar {
        /**
          * Fired on every keystroke with the current text.
         */
        "onSearchInput"?: (event: RcSearchBarCustomEvent<{ query: string }>) => void;
        /**
          * Fired when the user submits (Enter or button click).
         */
        "onSearchSubmit"?: (event: RcSearchBarCustomEvent<{ query: string }>) => void;
        /**
          * Placeholder text.
          * @default 'Search recipes…'
         */
        "placeholder"?: string;
        /**
          * Initial/controlled value of the search input.
          * @default ''
         */
        "value"?: string;
    }
    /**
     * An interactive (or read-only) star rating control.
     * Used e.g. on the recipe details page for the user to rate a recipe.
     */
    interface RcStarRating {
        /**
          * Max number of stars.
          * @default 5
         */
        "max"?: number;
        /**
          * Fired when the user picks a new rating (not fired in readonly mode).
         */
        "onRatingChange"?: (event: RcStarRatingCustomEvent<{ value: number }>) => void;
        /**
          * When false, stars are display-only (no hover/click interaction).
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Current rating value.
          * @default 0
         */
        "value"?: number;
    }

    interface RcPhotoCarouselAttributes {
        "alt": string;
        "label": string;
        "activeIndex": number;
        "showCounter": boolean;
        "showThumbs": boolean;
        "counterPosition": 'top-right' | 'bottom-right';
        "thumbsLayout": 'overlay' | 'inline';
    }
    interface RcRecipeCardAttributes {
        "recipeId": string;
        "name": string;
        "image": string;
        "category": string;
        "secondaryBadge": string;
        "meta": string;
        "isFavorite": boolean;
        "variant": 'default' | 'featured';
    }
    interface RcSearchBarAttributes {
        "value": string;
        "placeholder": string;
    }
    interface RcStarRatingAttributes {
        "value": number;
        "max": number;
        "readonly": boolean;
    }

    interface IntrinsicElements {
        "rc-photo-carousel": Omit<RcPhotoCarousel, keyof RcPhotoCarouselAttributes> & { [K in keyof RcPhotoCarousel & keyof RcPhotoCarouselAttributes]?: RcPhotoCarousel[K] } & { [K in keyof RcPhotoCarousel & keyof RcPhotoCarouselAttributes as `attr:${K}`]?: RcPhotoCarouselAttributes[K] } & { [K in keyof RcPhotoCarousel & keyof RcPhotoCarouselAttributes as `prop:${K}`]?: RcPhotoCarousel[K] };
        "rc-recipe-card": Omit<RcRecipeCard, keyof RcRecipeCardAttributes> & { [K in keyof RcRecipeCard & keyof RcRecipeCardAttributes]?: RcRecipeCard[K] } & { [K in keyof RcRecipeCard & keyof RcRecipeCardAttributes as `attr:${K}`]?: RcRecipeCardAttributes[K] } & { [K in keyof RcRecipeCard & keyof RcRecipeCardAttributes as `prop:${K}`]?: RcRecipeCard[K] } & OneOf<"recipeId", RcRecipeCard["recipeId"], RcRecipeCardAttributes["recipeId"]> & OneOf<"name", RcRecipeCard["name"], RcRecipeCardAttributes["name"]>;
        "rc-search-bar": Omit<RcSearchBar, keyof RcSearchBarAttributes> & { [K in keyof RcSearchBar & keyof RcSearchBarAttributes]?: RcSearchBar[K] } & { [K in keyof RcSearchBar & keyof RcSearchBarAttributes as `attr:${K}`]?: RcSearchBarAttributes[K] } & { [K in keyof RcSearchBar & keyof RcSearchBarAttributes as `prop:${K}`]?: RcSearchBar[K] };
        "rc-star-rating": Omit<RcStarRating, keyof RcStarRatingAttributes> & { [K in keyof RcStarRating & keyof RcStarRatingAttributes]?: RcStarRating[K] } & { [K in keyof RcStarRating & keyof RcStarRatingAttributes as `attr:${K}`]?: RcStarRatingAttributes[K] } & { [K in keyof RcStarRating & keyof RcStarRatingAttributes as `prop:${K}`]?: RcStarRating[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A photo carousel: a main image with prev/next buttons, an optional
             * "n / total" counter, and an optional thumbnail strip — driven by
             * keyboard (arrow keys), touch (swipe), and mouse alike.
             * Consolidates the two carousels that used to be hand-rolled independently
             * for the recipe detail hero and the recipe-form photo preview: same
             * WAI-ARIA pattern (a focusable `role="group"` region owning arrow-key
             * nav, with prev/next also reachable as real buttons), same swipe
             * gesture, same broken-image handling — just themed differently via
             * `counterPosition`/`thumbsLayout` and the `--rc-carousel-*` CSS
             * properties instead of two copies of the logic.
             */
            "rc-photo-carousel": LocalJSX.IntrinsicElements["rc-photo-carousel"] & JSXBase.HTMLAttributes<HTMLRcPhotoCarouselElement>;
            /**
             * A card that displays a recipe summary.
             * Consumers pass recipe data via props and listen for the `favoriteToggle`
             * custom event to react to favorite/unfavorite clicks. A named `actions`
             * slot lets the host app inject extra buttons (e.g. "Edit", "Delete") —
             * they appear as an overlay on the image, revealed on hover/focus.
             */
            "rc-recipe-card": LocalJSX.IntrinsicElements["rc-recipe-card"] & JSXBase.HTMLAttributes<HTMLRcRecipeCardElement>;
            /**
             * A search input with a submit button. Extra filter controls (selects,
             * checkboxes, etc.) can be projected via the default slot, so the host
             * app controls filter UI while this component only owns the text query.
             */
            "rc-search-bar": LocalJSX.IntrinsicElements["rc-search-bar"] & JSXBase.HTMLAttributes<HTMLRcSearchBarElement>;
            /**
             * An interactive (or read-only) star rating control.
             * Used e.g. on the recipe details page for the user to rate a recipe.
             */
            "rc-star-rating": LocalJSX.IntrinsicElements["rc-star-rating"] & JSXBase.HTMLAttributes<HTMLRcStarRatingElement>;
        }
    }
}
